### ISSUE TITLE
[Feature Request] dask.array and xarray as backend.

### ISSUE THREAD

**Issue by gRox167** [fferflo/einx#5]
# Required prerequisites
 I have searched the [Issue Tracker](https://github.com/fferflo/einx/issues) that this hasn't already been reported. (comment there if it has.)

# Motivation
Thanks for all the brilliant work of contributors of this repo!
`Dask.array` is a distributed version of `numpy` which could let research easily do parallel computing with cpu. 
`Xarray` is a named array package that is widely used in a lot of scientific area, and `xarray` also use `dask` as backend to support parallel computing.

If `einx` can support `dask.array` or `xarray` it would be super convenient to do large-scale (especially those who could not fit into memory) distributed data processing. This could be useful for areas like physics, astronomy, geoscience, microscopy and medical image.

# Solution
For dask.array, it would be easy. We can just utilize its lazy api, it is pretty much the same with numpy api.
However for xarray it is a little bit tricky, as xarray have names binding to each axis. We need to be careful when treating named dimension and the name in Einstein expression. 

# Alternatives
We can refer to [xarray-einstats](https://einstats.python.arviz.org/en/latest/).

**Comment by fferflo** [comment]
I added support for `dask.array` in https://github.com/fferflo/einx/commit/5fc0c09f0449df17fa59b8d8e6ae14c6b6e8b51d. Let me know if anything isn't working as expected :)

**Comment by gRox167** [comment]
Thanks for all the work you have done! I will update and have a check!
